//! Render an OpenWrt UCI shell script that recreates a host's WireGuard
//! interface and peers, plus a preflight block that installs whatever
//! packages are missing before touching UCI at all, using whichever
//! package manager the router actually has (`opkg` on OpenWrt <= 23.05,
//! `apk` on 24.10+).
//!
//! Paste the output into an SSH/terminal session on the router (or copy
//! it over and run it as a shell script).

use std::collections::HashSet;

use crate::host::WireGuardHost;
use crate::routeros::{eoip_tunnel_id, single_ip_address};

/// Package needed for `network.<iface>=interface; proto='wireguard'` to
/// come up. Just the LuCI protocol page, not `kmod-wireguard`/
/// `wireguard-tools` directly -- both `opkg` and `apk` resolve a package's
/// own declared dependencies automatically, and `luci-proto-wireguard`
/// already depends on both, so listing them here too would just be
/// duplicating dependency resolution the package manager already does.
const REQUIRED_PACKAGES: &[&str] = &["luci-proto-wireguard"];

/// Package needed for the optional EoIP (Ethernet over IP, MikroTik-
/// compatible) bridge: there's no in-tree netifd protocol for it, so this
/// rides on the third-party `eoip` package (kernel module + userspace
/// daemon, config lives in its own `/etc/config/eoip`). Just the LuCI page
/// here, same reasoning as `REQUIRED_PACKAGES` -- `luci-app-eoip` already
/// depends on `eoip`, so the package manager pulls it in on its own.
/// Only installed when [`OpenWrtOptions::eoip`] is on -- most plain
/// client<->host setups have no use for L2 bridging, so it's opt-in
/// rather than part of the baseline package set.
const EOIP_PACKAGES: &[&str] = &["luci-app-eoip"];

fn uci_str(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// UCI config/section names are shell-safe identifiers: keep only
/// alphanumerics and underscores, and never start with a digit (`uci`
/// itself is lenient about this, but a leading digit trips up some of its
/// own positional-index parsing, so it's not worth risking).
fn uci_ident(name: &str, fallback: &str) -> String {
    let cleaned: String = name
        .trim()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    let cleaned = cleaned.trim_matches('_').to_string();
    let cleaned = if cleaned.is_empty() { fallback.to_string() } else { cleaned };
    let cleaned = if cleaned.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("_{cleaned}")
    } else {
        cleaned
    };
    cleaned.chars().take(32).collect()
}

#[derive(Debug, Clone, Default)]
pub struct OpenWrtOptions {
    /// UCI network interface name (e.g. the "wg0" in `network.wg0`).
    /// Defaults to a sanitized version of the host's own name.
    pub interface_name: Option<String>,
    /// UCI firewall zone the interface is put into. Defaults to a fresh
    /// "wireguard" zone rather than folding it into an existing zone like
    /// "lan", since this script has no way to know the router's existing
    /// zone layout.
    pub firewall_zone: Option<String>,
    /// Also bridge every eligible peer link (one with a single-address
    /// AllowedIPs, i.e. it names one specific device rather than a routed
    /// subnet) over EoIP, using the third-party `eoip` package. Off by
    /// default -- see [`EOIP_PACKAGES`]'s doc comment for why this isn't
    /// installed unconditionally the way RouterOS's built-in EoIP support
    /// behaves.
    pub eoip: bool,
    /// When set, restricts [`Self::eoip`] to just these peers' public
    /// keys; `None` means every eligible peer.
    pub eoip_peers: Option<HashSet<String>>,
}

pub fn host_to_openwrt_script(host: &WireGuardHost, opts: &OpenWrtOptions) -> String {
    let iface = uci_ident(opts.interface_name.as_deref().unwrap_or(&host.name), "wg0");
    let zone = uci_ident(opts.firewall_zone.as_deref().unwrap_or("wireguard"), "wireguard");

    let mut lines: Vec<String> = vec![
        "#!/bin/sh".to_string(),
        format!("# OpenWrt UCI setup for '{}' -- generated by WireGuard Config Studio.", host.name),
        "# Review before running, especially the firewall section below --".to_string(),
        "# every network's zone layout is different.".to_string(),
        "set -e".to_string(),
        String::new(),
    ];

    // Every `uci -q delete X` below is followed by `|| true`: `-q` only
    // silences the printed "Entry not found" error, it does NOT change the
    // exit code, so on a router where X doesn't exist yet (a first run, or
    // just a fresh peer/zone) the bare command would still fail and, under
    // `set -e` above, silently abort the whole script before anything
    // useful happens. The delete-then-recreate pattern itself is still
    // wanted -- it's what keeps a rerun idempotent instead of piling up
    // duplicate `add_list` entries -- it just needs the `|| true` net so
    // the very first run (nothing to delete yet) doesn't die on it.

    // -- Preflight: install whatever's missing ---------------------------
    let mut pkg_list: Vec<&str> = REQUIRED_PACKAGES.to_vec();
    if opts.eoip {
        pkg_list.extend_from_slice(EOIP_PACKAGES);
    }
    let pkgs = pkg_list.join(" ");
    lines.push("# --- Ensure required packages are installed --------------------------".to_string());
    if opts.eoip {
        lines.push(
            "# NOTE: luci-app-eoip is a third-party community package (not in the".to_string(),
        );
        lines.push(
            "# official OpenWrt feeds) -- see https://github.com/bogdik/luci-app-eoip. If"
                .to_string(),
        );
        lines.push(
            "# the install below fails, your router's feeds don't have it; you'd need a".to_string(),
        );
        lines.push(
            "# custom feed or a self-built image that includes it.".to_string(),
        );
    }
    lines.push(format!("REQUIRED_PKGS=\"{pkgs}\""));
    lines.push("if command -v opkg >/dev/null 2>&1; then".to_string());
    lines.push("    MISSING=\"\"".to_string());
    lines.push("    for pkg in $REQUIRED_PKGS; do".to_string());
    lines.push("        opkg list-installed \"$pkg\" | grep -q \"^$pkg \" || MISSING=\"$MISSING $pkg\"".to_string());
    lines.push("    done".to_string());
    lines.push("    if [ -n \"$MISSING\" ]; then".to_string());
    lines.push("        echo \"Installing missing packages:$MISSING\"".to_string());
    lines.push("        opkg update".to_string());
    lines.push("        opkg install $MISSING".to_string());
    lines.push("    fi".to_string());
    lines.push("elif command -v apk >/dev/null 2>&1; then".to_string());
    lines.push("    MISSING=\"\"".to_string());
    lines.push("    for pkg in $REQUIRED_PKGS; do".to_string());
    lines.push("        apk info -e \"$pkg\" >/dev/null 2>&1 || MISSING=\"$MISSING $pkg\"".to_string());
    lines.push("    done".to_string());
    lines.push("    if [ -n \"$MISSING\" ]; then".to_string());
    lines.push("        echo \"Installing missing packages:$MISSING\"".to_string());
    lines.push("        apk update".to_string());
    lines.push("        apk add $MISSING".to_string());
    lines.push("    fi".to_string());
    lines.push("else".to_string());
    lines.push("    echo \"No opkg or apk found on this system -- install manually: $REQUIRED_PKGS\" >&2".to_string());
    lines.push("fi".to_string());
    lines.push(String::new());

    // -- Interface --------------------------------------------------------
    lines.push("# --- WireGuard interface ----------------------------------------------".to_string());
    lines.push(format!("uci -q delete network.{iface} || true"));
    lines.push(format!("uci set network.{iface}='interface'"));
    lines.push(format!("uci set network.{iface}.proto='wireguard'"));
    lines.push(format!(
        "uci set network.{iface}.private_key={}",
        uci_str(&host.private_key)
    ));
    if let Some(port) = host.listen_port {
        lines.push(format!("uci set network.{iface}.listen_port='{port}'"));
    }
    if let Some(mtu) = host.mtu {
        lines.push(format!("uci set network.{iface}.mtu='{mtu}'"));
    }
    if !host.address.is_empty() {
        lines.push(format!("uci -q delete network.{iface}.addresses || true"));
        for addr in &host.address {
            lines.push(format!("uci add_list network.{iface}.addresses={}", uci_str(addr)));
        }
    }
    if !host.dns.is_empty() {
        lines.push(format!(
            "# NOTE: DNS ({}) has no UCI option on the wireguard proto -- configure it via",
            host.dns.join(", ")
        ));
        lines.push("# /etc/config/dhcp (for a server) or this device's own resolver (for a client) instead.".to_string());
    }
    lines.push(String::new());

    // -- Peers --------------------------------------------------------------
    if !host.peers.is_empty() {
        lines.push("# --- Peers -------------------------------------------------------------".to_string());
        for (i, peer) in host.peers.iter().enumerate() {
            let label = peer.comment.clone().unwrap_or_else(|| format!("peer{}", i + 1));
            let section = uci_ident(&format!("{iface}_{label}"), &format!("{iface}_peer{}", i + 1));
            lines.push(format!("uci -q delete network.{section} || true"));
            lines.push(format!("uci set network.{section}='wireguard_{iface}'"));
            lines.push(format!(
                "uci set network.{section}.description={}",
                uci_str(&label)
            ));
            lines.push(format!(
                "uci set network.{section}.public_key={}",
                uci_str(&peer.public_key)
            ));
            if let Some(psk) = &peer.preshared_key {
                lines.push(format!(
                    "uci set network.{section}.preshared_key={}",
                    uci_str(psk)
                ));
            }
            if !peer.allowed_ips.is_empty() {
                lines.push(format!("uci -q delete network.{section}.allowed_ips || true"));
                for ip in &peer.allowed_ips {
                    lines.push(format!("uci add_list network.{section}.allowed_ips={}", uci_str(ip)));
                }
            }
            lines.push(format!("uci set network.{section}.route_allowed_ips='1'"));
            if let Some(ep) = &peer.endpoint {
                if let Some((ep_host, ep_port)) = ep.rsplit_once(':') {
                    if !ep_host.is_empty() {
                        lines.push(format!(
                            "uci set network.{section}.endpoint_host={}",
                            uci_str(ep_host)
                        ));
                        if !ep_port.is_empty() && ep_port.chars().all(|c| c.is_ascii_digit()) {
                            lines.push(format!("uci set network.{section}.endpoint_port='{ep_port}'"));
                        }
                    }
                } else if !ep.is_empty() {
                    lines.push(format!("uci set network.{section}.endpoint_host={}", uci_str(ep)));
                }
            }
            if let Some(ka) = peer.persistent_keepalive {
                lines.push(format!("uci set network.{section}.persistent_keepalive='{ka}'"));
            }
            lines.push(String::new());
        }
    }

    // -- EoIP (optional) -----------------------------------------------------
    if opts.eoip && !host.peers.is_empty() {
        lines.push("# --- EoIP (Ethernet over IP, MikroTik-compatible) ----------------------".to_string());
        lines.push("# Uses the third-party 'eoip' package's own /etc/config/eoip, not netifd's".to_string());
        lines.push("# 'network' config -- there's no in-tree UCI proto for it.".to_string());

        let mut used_ids: HashSet<u32> = HashSet::new();
        let mut any_real_eoip = false;
        for peer in &host.peers {
            if opts.eoip_peers.as_ref().is_some_and(|set| !set.contains(&peer.public_key)) {
                continue;
            }
            let label = peer.comment.clone().unwrap_or_else(|| peer.public_key.chars().take(8).collect());
            let remote_ip = match single_ip_address(&peer.allowed_ips) {
                Some(ip) => ip,
                None => {
                    lines.push(format!(
                        "# Skipped EoIP to {label}: its AllowedIPs isn't a single address (e.g. a \
                         routed subnet or 0.0.0.0/0), so there's no one specific device to bridge to."
                    ));
                    continue;
                }
            };
            any_real_eoip = true;

            let mut id = eoip_tunnel_id(&host.public_key, &peer.public_key);
            let mut attempts = 0;
            while used_ids.contains(&id) && attempts < 70000 {
                id = if id < 65535 { id + 1 } else { 1 };
                attempts += 1;
            }
            used_ids.insert(id);

            let section = uci_ident(&format!("{iface}_eoip_{label}"), &format!("{iface}_eoip{id}"));
            lines.push(format!("uci -q delete eoip.{section} || true"));
            lines.push(format!("uci set eoip.{section}='eoip'"));
            lines.push(format!("uci set eoip.{section}.enabled='1'"));
            // "name" picks the numeric suffix of the resulting zeoip<N>
            // interface -- purely local, so reusing the same number as
            // "idtun" is just a convenient way to keep them from clashing
            // with each other, not a protocol requirement.
            lines.push(format!("uci set eoip.{section}.name='{id}'"));
            lines.push(format!("uci set eoip.{section}.idtun='{id}'"));
            lines.push(format!("uci set eoip.{section}.dst={}", uci_str(&remote_ip)));
            lines.push(format!("uci set eoip.{section}.dynamic='0'"));
            lines.push(format!(
                "# -> creates interface zeoip{id} for {label}; add it to a bridge yourself if this"
            ));
            lines.push("#    link should extend a LAN (e.g. `uci add_list network.br_lan.ifname='zeoip".to_string() + &id.to_string() + "'`),");
            lines.push("#    or leave it unbridged for a routed L2 hop.".to_string());
        }
        if any_real_eoip {
            lines.push("uci commit eoip".to_string());
            // "|| true": this is a third-party init script (not part of
            // base OpenWrt), and less mature ones are known to return
            // non-zero on a first start / when nothing was previously
            // running to stop -- shouldn't abort the script over that,
            // especially since every uci change above already committed.
            lines.push("/etc/init.d/eoip enable || true".to_string());
            lines.push("/etc/init.d/eoip restart || true".to_string());
        }
        lines.push(String::new());
    }

    // -- Firewall -------------------------------------------------------------
    lines.push("# --- Firewall ------------------------------------------------------------".to_string());
    lines.push(format!("uci -q delete firewall.{zone} || true"));
    lines.push(format!("uci set firewall.{zone}='zone'"));
    lines.push(format!("uci set firewall.{zone}.name={}", uci_str(&zone)));
    lines.push(format!("uci add_list firewall.{zone}.network={}", uci_str(&iface)));
    lines.push(format!("uci set firewall.{zone}.input='ACCEPT'"));
    lines.push(format!("uci set firewall.{zone}.output='ACCEPT'"));
    lines.push(format!("uci set firewall.{zone}.forward='REJECT'"));
    lines.push(
        "# NOTE: add a forwarding rule if this tunnel should reach another zone, e.g. 'lan':"
            .to_string(),
    );
    lines.push("#   uci add firewall forwarding".to_string());
    lines.push(format!("#   uci set firewall.@forwarding[-1].src='{zone}'"));
    lines.push("#   uci set firewall.@forwarding[-1].dest='lan'".to_string());
    if let Some(port) = host.listen_port {
        let rule = uci_ident(&format!("{iface}_allow"), "wg_allow");
        lines.push(format!("uci -q delete firewall.{rule} || true"));
        lines.push(format!("uci set firewall.{rule}='rule'"));
        lines.push(format!(
            "uci set firewall.{rule}.name={}",
            uci_str(&format!("Allow WireGuard ({iface})"))
        ));
        lines.push(format!("uci set firewall.{rule}.src='wan'"));
        lines.push(format!("uci set firewall.{rule}.proto='udp'"));
        lines.push(format!("uci set firewall.{rule}.dest_port='{port}'"));
        lines.push(format!("uci set firewall.{rule}.target='ACCEPT'"));
    }
    lines.push(String::new());

    lines.push("uci commit network".to_string());
    lines.push("uci commit firewall".to_string());
    lines.push("/etc/init.d/network restart".to_string());
    lines.push("/etc/init.d/firewall restart".to_string());
    lines.push(String::new());
    lines.push(format!(
        "# Verify with: ubus call network.interface.{iface} status"
    ));

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host::HostOptions;
    use crate::peer::Peer;

    #[test]
    fn script_installs_packages_and_configures_interface_and_peers() {
        let mut host = WireGuardHost::new(
            "office-hq",
            HostOptions {
                address: vec!["10.10.0.1/24".into()],
                listen_port: Some(51820),
                ..Default::default()
            },
        )
        .unwrap();
        host.add_peer(
            Peer::build(
                WireGuardHost::simple("alice").unwrap().public_key,
                vec!["10.10.0.2/32".into()],
                Some("203.0.113.9:51820".into()),
                Some(25),
                None,
                Some("alice".into()),
            )
            .unwrap(),
        );

        let script = host_to_openwrt_script(&host, &OpenWrtOptions::default());

        assert!(script.contains("REQUIRED_PKGS=\"luci-proto-wireguard\""));
        assert!(script.contains("command -v opkg"));
        assert!(script.contains("command -v apk"));
        assert!(script.contains("uci set network.office_hq='interface'"));
        assert!(script.contains("uci set network.office_hq.proto='wireguard'"));
        assert!(script.contains("uci add_list network.office_hq.addresses='10.10.0.1/24'"));
        assert!(script.contains("uci set network.office_hq_alice='wireguard_office_hq'"));
        assert!(script.contains("uci add_list network.office_hq_alice.allowed_ips='10.10.0.2/32'"));
        assert!(script.contains("uci set network.office_hq_alice.endpoint_host='203.0.113.9'"));
        assert!(script.contains("uci set network.office_hq_alice.endpoint_port='51820'"));
        assert!(script.contains("uci set network.office_hq_alice.persistent_keepalive='25'"));
        assert!(script.contains("uci commit network"));
        assert!(script.contains("uci commit firewall"));
        assert!(!script.contains("eoip"), "EoIP is opt-in and must not appear when OpenWrtOptions::eoip is off");
    }

    #[test]
    fn eoip_off_by_default_but_generates_a_matching_id_on_both_ends_when_on() {
        let host_a = WireGuardHost::new("host-a", HostOptions { address: vec!["172.16.1.1/24".into()], ..Default::default() }).unwrap();
        let host_b = WireGuardHost::new("host-b", HostOptions { address: vec!["172.16.2.1/24".into()], ..Default::default() }).unwrap();

        let mut a = host_a.clone();
        a.add_peer(Peer::build(host_b.public_key.clone(), vec!["172.16.2.1/32".into()], Some("203.0.113.2:51820".into()), Some(25), None, Some("host-b".into())).unwrap());
        let mut b = host_b.clone();
        b.add_peer(Peer::build(host_a.public_key.clone(), vec!["172.16.1.1/32".into()], None, Some(25), None, Some("host-a".into())).unwrap());

        let opts = OpenWrtOptions { eoip: true, ..Default::default() };
        let script_a = host_to_openwrt_script(&a, &opts);
        let script_b = host_to_openwrt_script(&b, &opts);

        assert!(script_a.contains("REQUIRED_PKGS=\"luci-proto-wireguard luci-app-eoip\""));
        assert!(script_a.contains("github.com/bogdik/luci-app-eoip"), "third-party package needs the not-in-official-feeds caveat");
        assert!(script_a.contains("uci set eoip.host_a_eoip_host_b='eoip'"));
        // dst is the peer's own tunnel-overlay address (from its
        // AllowedIPs), not its public Endpoint -- EoIP/GRE rides *inside*
        // the already-established WireGuard tunnel, so the only address
        // that matters here is the one reachable over that tunnel.
        assert!(script_a.contains("uci set eoip.host_a_eoip_host_b.dst='172.16.2.1'"));
        assert!(script_a.contains("uci commit eoip"));

        let id_a = extract_uci_value(&script_a, "idtun");
        let id_b = extract_uci_value(&script_b, "idtun");
        assert_eq!(id_a, id_b, "both ends of the same link must agree on the same idtun");
    }

    #[test]
    fn eoip_skips_peers_whose_allowed_ips_is_a_routed_subnet() {
        let host = WireGuardHost::new("gw", HostOptions { address: vec!["10.0.0.1/24".into()], ..Default::default() }).unwrap();
        let mut host = host;
        host.add_peer(Peer::build(WireGuardHost::simple("branch").unwrap().public_key, vec!["0.0.0.0/0".into()], None, None, None, Some("branch".into())).unwrap());

        let script = host_to_openwrt_script(&host, &OpenWrtOptions { eoip: true, ..Default::default() });
        assert!(script.contains("Skipped EoIP to branch"));
        assert!(!script.contains("uci commit eoip"), "no eligible peer -- nothing should be committed");
    }

    fn extract_uci_value(script: &str, option: &str) -> String {
        script
            .lines()
            .find(|l| l.contains(&format!(".{option}=")))
            .unwrap_or_else(|| panic!("no line setting .{option}= in:\n{script}"))
            .rsplit('=')
            .next()
            .unwrap()
            .trim_matches('\'')
            .to_string()
    }

    #[test]
    fn every_uci_delete_is_guarded_against_a_first_run_with_nothing_to_delete() {
        // `uci -q delete X` still exits non-zero if X doesn't exist -- `-q`
        // only silences the printed error, not the exit code. Under this
        // script's `set -e`, an unguarded delete would abort the whole run
        // on a fresh router where nothing has been configured yet.
        let mut host = WireGuardHost::new(
            "gw",
            HostOptions { address: vec!["10.0.0.1/24".into()], listen_port: Some(51820), ..Default::default() },
        )
        .unwrap();
        host.add_peer(
            Peer::build(WireGuardHost::simple("alice").unwrap().public_key, vec!["10.0.0.2/32".into()], None, None, None, Some("alice".into())).unwrap(),
        );

        let script = host_to_openwrt_script(&host, &OpenWrtOptions { eoip: true, ..Default::default() });
        let mut saw_a_delete = false;
        for line in script.lines() {
            if line.trim_start().starts_with("uci -q delete") {
                saw_a_delete = true;
                assert!(line.ends_with("|| true"), "unguarded delete would abort a fresh-router run: {line}");
            }
        }
        assert!(saw_a_delete, "test setup should have exercised at least one delete line");
    }

    #[test]
    fn section_names_never_start_with_a_digit() {
        assert_eq!(uci_ident("9-office", "fallback"), "_9_office");
        assert_eq!(uci_ident("", "wg0"), "wg0");
    }
}
