//! Render a shell script that brings up a WireGuard tunnel on pfSense
//! using FreeBSD's own kernel WireGuard (`if_wg`, native since FreeBSD
//! 13 / pfSense 2.7.0) directly via `ifconfig`/`wg(8)` -- deliberately
//! *not* by touching pfSense's own WireGuard GUI package's `config.xml`
//! entries.
//!
//! That XML/PHP schema has changed across pfSense/package versions (the
//! original community package, Netgate's 2.5.0+ GUI rewrite, and the
//! version bundled since 2.7.0 all use different `$config` array shapes),
//! and getting it wrong doesn't fail cleanly the way a bad `uci set` or
//! RouterOS `/import` does -- a malformed `config.xml` can leave the whole
//! firewall's configuration broken, not just WireGuard. FreeBSD's own
//! `wg(8)` config format and `ifconfig`/`rc.conf.local` conventions, by
//! contrast, are stable, version-independent, and well documented, so
//! that's what this generates against instead.
//!
//! Trade-off this makes deliberately: the resulting tunnel won't show up
//! on pfSense's own VPN > WireGuard page, since it never touches that
//! package's config at all. If that GUI package is also managing
//! WireGuard on the same device, running both risks the two stepping on
//! each other.

use crate::host::WireGuardHost;

fn sh_str(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// The config body understood by FreeBSD's `wg(8)` (`wg syncconf`/`wg
/// setconf`), which is WireGuard's own protocol-level config format --
/// only `PrivateKey`/`ListenPort`/`FwMark` and, per peer,
/// `PublicKey`/`PresharedKey`/`AllowedIPs`/`Endpoint`/
/// `PersistentKeepalive`. It does *not* understand wg-quick's extensions
/// (`Address`, `DNS`, `MTU`, `PostUp`, ...) -- FreeBSD's `wg` utility
/// rejects those outright, which is why the interface's address is set
/// separately via `ifconfig` in [`host_to_pfsense_script`] instead of
/// being embedded here.
fn wg_setconf_body(host: &WireGuardHost) -> String {
    let mut lines = vec!["[Interface]".to_string(), format!("PrivateKey = {}", host.private_key)];
    if let Some(port) = host.listen_port {
        lines.push(format!("ListenPort = {port}"));
    }
    if let Some(fw) = &host.fw_mark {
        lines.push(format!("FwMark = {fw}"));
    }
    for peer in &host.peers {
        lines.push(String::new());
        lines.push("[Peer]".to_string());
        lines.push(format!("PublicKey = {}", peer.public_key));
        if let Some(psk) = &peer.preshared_key {
            lines.push(format!("PresharedKey = {psk}"));
        }
        if !peer.allowed_ips.is_empty() {
            lines.push(format!("AllowedIPs = {}", peer.allowed_ips.join(", ")));
        }
        if let Some(ep) = &peer.endpoint {
            lines.push(format!("Endpoint = {ep}"));
        }
        if let Some(ka) = peer.persistent_keepalive {
            lines.push(format!("PersistentKeepalive = {ka}"));
        }
    }
    lines.join("\n")
}

#[derive(Debug, Clone, Default)]
pub struct PfSenseOptions {
    /// The cloned interface's name. FreeBSD `wg` interfaces are named
    /// `wgN` (a clone of the `wg` interface family), not arbitrary names
    /// the way a Linux `ip link` interface can be -- defaults to `wg0`.
    pub interface_name: Option<String>,
}

pub fn host_to_pfsense_script(host: &WireGuardHost, opts: &PfSenseOptions) -> String {
    let iface = opts.interface_name.as_deref().unwrap_or("wg0");
    let conf_dir = "/usr/local/etc/wireguard";
    let conf_file = format!("{conf_dir}/{iface}.conf");
    let rc_script = format!("/usr/local/etc/rc.d/wg-{iface}-syncconf.sh");

    let mut lines: Vec<String> = vec![
        "#!/bin/sh".to_string(),
        format!("# pfSense / FreeBSD native WireGuard setup for '{}' -- generated by", host.name),
        "# WireGuard Config Studio. Review before running.".to_string(),
        "#".to_string(),
        "# This drives FreeBSD's kernel WireGuard (if_wg) directly via ifconfig/wg(8),".to_string(),
        "# NOT pfSense's own WireGuard GUI package -- this tunnel will not appear on".to_string(),
        "# the VPN > WireGuard page, and running both on the same interface name can".to_string(),
        "# conflict. Requires pfSense 2.7.0+ / a FreeBSD with native WireGuard support.".to_string(),
        "set -e".to_string(),
        String::new(),
    ];

    lines.push("# --- Ensure the WireGuard kernel module and wg(8) are available -------".to_string());
    lines.push("kldload if_wg 2>/dev/null || true".to_string());
    lines.push("if ! command -v wg >/dev/null 2>&1; then".to_string());
    lines.push("    echo \"wg(8) not found -- install it with: pkg install wireguard-tools\" >&2".to_string());
    lines.push("    exit 1".to_string());
    lines.push("fi".to_string());
    lines.push(String::new());

    lines.push("# --- WireGuard config (protocol-level only -- see wg_setconf_body's doc".to_string());
    lines.push("# comment for why Address/DNS/MTU aren't in here) --------------------".to_string());
    lines.push(format!("mkdir -p {}", sh_str(conf_dir)));
    lines.push(format!("chmod 700 {}", sh_str(conf_dir)));
    lines.push(format!("cat > {} <<'WG_STUDIO_EOF'", sh_str(&conf_file)));
    lines.push(wg_setconf_body(host));
    lines.push("WG_STUDIO_EOF".to_string());
    lines.push(format!("chmod 600 {}", sh_str(&conf_file)));
    lines.push(String::new());

    lines.push("# --- Bring the interface up now ---------------------------------------".to_string());
    lines.push(format!("ifconfig {iface} create 2>/dev/null || true"));
    lines.push(format!("wg syncconf {iface} {}", sh_str(&conf_file)));
    if !host.address.is_empty() {
        let addr_args: Vec<String> = host.address.iter().map(|a| sh_str(a)).collect();
        let mut cmd = format!("ifconfig {iface} inet {}", addr_args.join(" "));
        if let Some(mtu) = host.mtu {
            cmd.push_str(&format!(" mtu {mtu}"));
        }
        cmd.push_str(" up");
        lines.push(cmd);
    } else {
        lines.push(format!("ifconfig {iface} up"));
    }
    lines.push(String::new());

    lines.push("# --- Persist across reboot: pfSense regenerates /etc/rc.conf from its".to_string());
    lines.push("# own config.xml on every boot, but leaves /etc/rc.conf.local alone --".to_string());
    lines.push("# that's where any hand-added rc.conf entries need to live instead. ---".to_string());
    let cloned_line = format!("cloned_interfaces=\"{iface}\"");
    lines.push(format!(
        "grep -qF {} /etc/rc.conf.local 2>/dev/null || echo {} >> /etc/rc.conf.local",
        sh_str(&cloned_line),
        sh_str(&cloned_line)
    ));
    if !host.address.is_empty() {
        let addr_str = host.address.join(" ");
        let mtu_part = host.mtu.map(|m| format!(" mtu {m}")).unwrap_or_default();
        let ifconfig_line = format!("ifconfig_{iface}=\"inet {addr_str}{mtu_part} up\"");
        lines.push(format!(
            "grep -qF {} /etc/rc.conf.local 2>/dev/null || echo {} >> /etc/rc.conf.local",
            sh_str(&ifconfig_line),
            sh_str(&ifconfig_line)
        ));
    }
    lines.push(String::new());

    lines.push("# --- Re-apply the WireGuard config on every boot: cloned_interfaces/".to_string());
    lines.push("# ifconfig_* above only create the interface and set its address, they".to_string());
    lines.push("# don't load the private key/peers -- a small rc.d script does that. ---".to_string());
    lines.push(format!("cat > {} <<'RC_STUDIO_EOF'", sh_str(&rc_script)));
    lines.push("#!/bin/sh".to_string());
    lines.push(format!("# PROVIDE: wg_{iface}_syncconf"));
    lines.push("# REQUIRE: netif".to_string());
    lines.push(format!("/usr/bin/wg syncconf {iface} {}", sh_str(&conf_file)));
    lines.push("RC_STUDIO_EOF".to_string());
    lines.push(format!("chmod +x {}", sh_str(&rc_script)));
    lines.push(String::new());

    lines.push(format!("echo \"Done. Verify with: wg show {iface}\""));

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host::HostOptions;
    use crate::peer::Peer;

    fn sample_host() -> WireGuardHost {
        let mut host = WireGuardHost::new(
            "office-hq",
            HostOptions {
                address: vec!["10.10.0.1/24".into()],
                listen_port: Some(51820),
                mtu: Some(1420),
                dns: vec!["1.1.1.1".into()], // should be ignored -- wg(8) doesn't understand DNS
                ..Default::default()
            },
        )
        .unwrap();
        host.add_peer(
            Peer::build(
                WireGuardHost::simple("alice").unwrap().public_key,
                vec!["10.10.0.2/32".into()],
                Some("203.0.113.9:51820".into()),
                Some(25),
                None,
                Some("alice".into()),
            )
            .unwrap(),
        );
        host
    }

    #[test]
    fn setconf_body_omits_wg_quick_only_fields() {
        let body = wg_setconf_body(&sample_host());
        assert!(body.contains("PrivateKey ="));
        assert!(body.contains("ListenPort = 51820"));
        assert!(body.contains("PublicKey ="));
        assert!(body.contains("AllowedIPs = 10.10.0.2/32"));
        assert!(body.contains("Endpoint = 203.0.113.9:51820"));
        assert!(body.contains("PersistentKeepalive = 25"));
        assert!(!body.contains("Address"), "wg(8) rejects Address in [Interface] -- must never appear here");
        assert!(!body.contains("DNS"), "wg(8) doesn't understand wg-quick's DNS directive");
        assert!(!body.contains("MTU"), "wg(8) doesn't understand wg-quick's MTU directive");
    }

    #[test]
    fn script_sets_address_via_ifconfig_not_the_conf_file() {
        let script = host_to_pfsense_script(&sample_host(), &PfSenseOptions::default());
        assert!(script.contains("wg syncconf wg0 '/usr/local/etc/wireguard/wg0.conf'"));
        assert!(script.contains("ifconfig wg0 inet '10.10.0.1/24' mtu 1420 up"));
        assert!(script.contains("kldload if_wg"));
        assert!(script.contains("/etc/rc.conf.local"));
        assert!(script.contains("/usr/local/etc/rc.d/wg-wg0-syncconf.sh"));
    }

    #[test]
    fn custom_interface_name_is_used_throughout() {
        let opts = PfSenseOptions { interface_name: Some("wg1".to_string()) };
        let script = host_to_pfsense_script(&sample_host(), &opts);
        assert!(script.contains("wg syncconf wg1"));
        assert!(script.contains("ifconfig wg1 create"));
        assert!(!script.contains("wg0"));
    }
}
