//! Render a RouterOS (MikroTik) CLI script that recreates a host's
//! WireGuard interface, address(es), peers, an EoIP tunnel riding on top
//! of each point-to-point peer, a basic firewall allowance for the
//! tunnel, and static routes for each peer's AllowedIPs.
//!
//! Paste the output directly into an SSH/terminal session on the router
//! (RouterOS v7+, which has native WireGuard support).

use std::collections::{HashMap, HashSet};

use sha2::{Digest, Sha256};

use crate::host::WireGuardHost;

fn routeros_str(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\\\""))
}

fn routeros_interface_name(name: &str, fallback: &str) -> String {
    let cleaned: String = name
        .trim()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '-' })
        .collect();
    let cleaned = cleaned.trim_matches('-');
    let result = if cleaned.is_empty() { fallback } else { cleaned };
    result.chars().take(32).collect()
}

/// Return the bare IP if `cidr_list` is exactly one /32 (or /128) address,
/// else `None`. EoIP needs one specific remote endpoint, not a routed
/// subnet, so a peer whose AllowedIPs is a range (e.g. a full-tunnel
/// 0.0.0.0/0) doesn't have a usable "other end" address.
pub fn single_ip_address(cidr_list: &[String]) -> Option<String> {
    if cidr_list.len() != 1 {
        return None;
    }
    let net: ipnet::IpNet = cidr_list[0].parse().ok()?;
    let is_host = match net {
        ipnet::IpNet::V4(n) => n.prefix_len() == 32,
        ipnet::IpNet::V6(n) => n.prefix_len() == 128,
    };
    if !is_host {
        return None;
    }
    Some(net.network().to_string())
}

/// Return the bare IP of the first entry in `cidr_list`, regardless of its
/// prefix length. Unlike `single_ip_address()`, this doesn't require a
/// lone /32 -- it's for reading "this host's own address" out of a normal
/// subnet-style Address field like 10.10.0.1/24.
pub fn bare_ip_address(cidr_list: &[String]) -> Option<String> {
    let first = cidr_list.first()?;
    if let Ok(net) = first.parse::<ipnet::IpNet>() {
        return Some(net.addr().to_string());
    }
    first.split('/').next().map(str::to_string)
}

/// A tunnel-id derived from both peers' WireGuard public keys.
/// Order-independent so generating the script from either side of the
/// link produces the same id.
fn eoip_tunnel_id(pubkey_a: &str, pubkey_b: &str) -> u32 {
    let mut pair = [pubkey_a, pubkey_b];
    pair.sort();
    let joined = format!("{}|{}", pair[0], pair[1]);
    let digest = Sha256::digest(joined.as_bytes());
    let hex = digest.iter().map(|b| format!("{b:02x}")).collect::<String>();
    // Interpret the hex digest as a big number mod 65000, +1, same as the
    // Python `int(digest, 16) % 65000 + 1`. A u128 easily covers this: we
    // only need the low-order bits for a modulus this small, so folding
    // the digest bytes through a running remainder avoids needing
    // bignum arithmetic.
    let mut rem: u64 = 0;
    for ch in hex.chars() {
        let digit = ch.to_digit(16).unwrap() as u64;
        rem = (rem * 16 + digit) % 65000;
    }
    (rem as u32) + 1
}

#[derive(Debug, Clone, Default)]
pub struct RouterOsOptions {
    /// Maps a peer's public_key to the bare IP that peer is actually
    /// configured with (its own Address field) -- this is what EoIP's
    /// remote-address is built from.
    pub peer_remote_addresses: HashMap<String, String>,
    /// Maps a peer's public_key to the EoIP tunnel-id to use for it.
    pub peer_tunnel_ids: HashMap<String, u32>,
    pub interface_name: Option<String>,
}

pub fn host_to_routeros_script(host: &WireGuardHost, opts: &RouterOsOptions) -> String {
    let iface = routeros_interface_name(opts.interface_name.as_deref().unwrap_or(&host.name), "wg0");
    let mut lines: Vec<String> = vec![
        format!("# RouterOS WireGuard setup for '{}'", host.name),
        "# Generated by WireGuard Config Studio -- review before applying,".to_string(),
        "# especially the firewall and route sections, since every network differs.".to_string(),
        String::new(),
        "/interface/wireguard".to_string(),
    ];

    let mut iface_cmd = vec![
        format!("add name={}", routeros_str(&iface)),
        format!("private-key={}", routeros_str(&host.private_key)),
    ];
    if let Some(p) = host.listen_port {
        iface_cmd.push(format!("listen-port={p}"));
    }
    if let Some(m) = host.mtu {
        iface_cmd.push(format!("mtu={m}"));
    }
    lines.push(iface_cmd.join(" "));
    lines.push(String::new());

    if !host.address.is_empty() {
        lines.push("/ip/address".to_string());
        for addr in &host.address {
            lines.push(format!(
                "add address={} interface={}",
                routeros_str(addr),
                routeros_str(&iface)
            ));
        }
        lines.push(String::new());
    }

    if !host.peers.is_empty() {
        lines.push("/interface/wireguard/peers".to_string());
        for peer in &host.peers {
            let mut cmd = vec![
                format!("add interface={}", routeros_str(&iface)),
                format!("public-key={}", routeros_str(&peer.public_key)),
            ];
            if !peer.allowed_ips.is_empty() {
                cmd.push(format!("allowed-address={}", peer.allowed_ips.join(",")));
            }
            if let Some(ep) = &peer.endpoint {
                if let Some((ep_host, ep_port)) = ep.rsplit_once(':') {
                    if !ep_host.is_empty() {
                        cmd.push(format!("endpoint-address={}", routeros_str(ep_host)));
                        if ep_port.chars().all(|c| c.is_ascii_digit()) && !ep_port.is_empty() {
                            cmd.push(format!("endpoint-port={ep_port}"));
                        }
                    }
                } else if !ep.is_empty() {
                    cmd.push(format!("endpoint-address={}", routeros_str(ep)));
                }
            }
            if let Some(ka) = peer.persistent_keepalive {
                cmd.push(format!("persistent-keepalive={ka}s"));
            }
            if let Some(psk) = &peer.preshared_key {
                cmd.push(format!("preshared-key={}", routeros_str(psk)));
            }
            if let Some(c) = &peer.comment {
                cmd.push(format!("comment={}", routeros_str(c)));
            }
            lines.push(cmd.join(" "));
        }
        lines.push(String::new());
    }

    let mut any_real_eoip = false;
    if !host.peers.is_empty() {
        let local_ip = bare_ip_address(&host.address);

        let mut eoip_lines: Vec<String> = Vec::new();
        let mut used_tunnel_ids: HashSet<u32> = HashSet::new();

        for peer in &host.peers {
            let label = peer
                .comment
                .clone()
                .unwrap_or_else(|| peer.public_key.chars().take(8).collect());

            let remote_ip = opts
                .peer_remote_addresses
                .get(&peer.public_key)
                .cloned()
                .or_else(|| single_ip_address(&peer.allowed_ips));

            let remote_ip = match remote_ip {
                Some(ip) => ip,
                None => {
                    eoip_lines.push(format!(
                        "# Skipped EoIP to {label}: no known address for it (its AllowedIPs is a \
                         range, e.g. a full-tunnel 0.0.0.0/0, not one address)."
                    ));
                    continue;
                }
            };
            let local_ip = match &local_ip {
                Some(ip) => ip.clone(),
                None => {
                    eoip_lines.push(format!(
                        "# Skipped EoIP to {label}: this host has no address of its own."
                    ));
                    continue;
                }
            };
            any_real_eoip = true;

            let mut tunnel_id = opts
                .peer_tunnel_ids
                .get(&peer.public_key)
                .copied()
                .unwrap_or_else(|| eoip_tunnel_id(&host.public_key, &peer.public_key));
            let original_id = tunnel_id;
            let mut attempts = 0;
            while used_tunnel_ids.contains(&tunnel_id) && attempts < 70000 {
                tunnel_id = if tunnel_id < 65535 { tunnel_id + 1 } else { 1 };
                attempts += 1;
            }
            used_tunnel_ids.insert(tunnel_id);
            if tunnel_id != original_id {
                eoip_lines.push(format!(
                    "# NOTE: tunnel-id {original_id} for {label} was already used by another client \
                     on this host; auto-adjusted to {tunnel_id} to avoid a conflict. If {original_id} \
                     was meant to be fixed, update the other router to match {tunnel_id} instead."
                ));
            }

            let eoip_name = format!(
                "eoip-{}",
                routeros_interface_name(peer.comment.as_deref().unwrap_or("peer"), "peer")
            );
            let cmd = vec![
                format!("add name={}", routeros_str(&eoip_name)),
                format!("remote-address={}", routeros_str(&remote_ip)),
                format!("local-address={}", routeros_str(&local_ip)),
                format!("tunnel-id={tunnel_id}"),
                format!("comment={}", routeros_str(&format!("EoIP to {label}, over WireGuard"))),
            ];
            eoip_lines.push(cmd.join(" "));
        }

        if any_real_eoip {
            lines.push("/interface/eoip".to_string());
            lines.extend(eoip_lines);
            lines.push(
                "# Each eoip-* interface carries raw Ethernet over the WireGuard tunnel. Add it to a"
                    .to_string(),
            );
            lines.push(
                "# bridge (e.g. /interface/bridge/port add bridge=your-bridge interface=eoip-...) to"
                    .to_string(),
            );
            lines.push("# extend a LAN across the link, or leave it unbridged for a routed L2 hop.".to_string());
            lines.push(String::new());
        } else if !eoip_lines.is_empty() {
            lines.push(
                "# No EoIP tunnels generated: none of this host's peers have a single-address \
                 AllowedIPs to target."
                    .to_string(),
            );
            lines.push(String::new());
        }
    }

    lines.push("/ip/firewall/filter".to_string());
    if let Some(p) = host.listen_port {
        lines.push(format!(
            "add chain=input protocol=udp dst-port={p} action=accept comment={}",
            routeros_str(&format!("Allow WireGuard ({iface})"))
        ));
    }
    if any_real_eoip {
        lines.push(format!(
            "add chain=input protocol=gre action=accept comment={}",
            routeros_str("Allow EoIP (GRE)")
        ));
    }
    lines.push(format!(
        "add chain=forward in-interface={} action=accept comment={}",
        routeros_str(&iface),
        routeros_str(&format!("Allow {iface} forward in"))
    ));
    lines.push(format!(
        "add chain=forward out-interface={} action=accept comment={}",
        routeros_str(&iface),
        routeros_str(&format!("Allow {iface} forward out"))
    ));
    lines.push(String::new());

    let mut route_targets: Vec<String> = Vec::new();
    for peer in &host.peers {
        for allowed in &peer.allowed_ips {
            if !route_targets.contains(allowed) {
                route_targets.push(allowed.clone());
            }
        }
    }
    if !route_targets.is_empty() {
        lines.push("/ip/route".to_string());
        for target in &route_targets {
            if target == "0.0.0.0/0" || target == "::/0" {
                lines.push(format!(
                    "# NOTE: {target} becomes your default route via {iface} -- adjust distance= \
                     below if you already have one"
                ));
            }
            lines.push(format!(
                "add dst-address={} gateway={} comment={}",
                routeros_str(target),
                routeros_str(&iface),
                routeros_str(&format!("via {iface}"))
            ));
        }
        lines.push(String::new());
    }

    lines.push(format!(
        "/interface/wireguard/print where name={}",
        routeros_str(&iface)
    ));
    lines.push(format!(
        "# Verify peers with: /interface/wireguard/peers/print where interface={}",
        routeros_str(&iface)
    ));

    lines.join("\n")
}
